---
# tasks file for arillso.motd

- name: add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: add distribution tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  tags:
    - configuration
